<?php
function title_case_menu() {
  $items = array();
  $items['title_case'] = array(
    'title' => 'Title case',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('title_case_form'),
  );

  $items['success'] = array(
    'title' => 'Success',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'title_case_success',
  );
  return $items;
}

function title_case_form() {
  $form = array();
  $form['user_input'] = array(
    '#title' => 'Enter text',
    '#type' => 'textfield',
    '#description' => t('Please enter some text.'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Calculate Title Case',
  );

  return $form;
}

function title_case_form_submit($form, &$form_state) {
  $text_input = $form_state['values']['user_input'];
  $text_output = strtoupper($text_input);

  $_SESSION['uppr_case_output'] = $text_output;
  $form_state['redirect'] = "success";
}

function title_case_success() {
  $output = $_SESSION['uppr_case_output'];
  return " $output ";
}
